from django.urls import path

from . import views

urlpatterns = [
    path(
        "",
        views.StudentDashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "lessons/",
        views.LessonHomeView.as_view(),
        name="lessons",
    ),
    path(
        "purchased-courses/",
        views.StudentPurchasedCoursesView.as_view(),
        name="purchased-courses",
    ),
    path(
        "messages/",
        views.StudentMessagesView.as_view(),
        name="messages",
    ),
    path(
        "notifications/",
        views.StudentNotificationsView.as_view(),
        name="notifications",
    ),
    path(
        "reviews/",
        views.StudentReviewsView.as_view(),
        name="reviews",
    ),
    path(
        "certificates/",
        views.StudentCertificateView.as_view(),
        name="certificates",
    ),
    path(
        "credits/",
        views.StudentCreditView.as_view(),
        name="credits",
    ),
    path(
        "statements/",
        views.StudentTransactionView.as_view(),
        name="statements",
    ),
    path(
        "saved-courses/",
        views.StudentSavedCoursesView.as_view(),
        name="saved_courses",
    ),
    path(
        "courses/shoppings/",
        views.StudentShoppingCartView.as_view(),
        name="shopping_courses",
    ),
]
