# Generated by Django 4.2.14 on 2024-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_remove_savedcourse_course_savedcourse_courses'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(blank=True, to='school.course'),
        ),
    ]
