# Generated by Django 4.2.14 on 2024-11-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_profile_first_name_profile_headline_and_more'),
        ('purchases', '0003_alter_cart_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_cart', to='users.profile'),
        ),
    ]
