# Generated by Django 4.2.14 on 2024-11-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_alter_category_options'),
        ('users', '0007_profile_username'),
        ('purchases', '0004_alter_cart_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('discount_percent', models.PositiveIntegerField()),
                ('start_timestamp', models.DateTimeField()),
                ('ended_timestamp', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='school.course')),
                ('students', models.ManyToManyField(blank=True, related_name='applied_coupons', to='users.profile')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ('-start_timestamp',),
            },
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('start_timestamp__lte', models.F('ended_timestamp'))), name='coupon_start_timestamp_lte_ended_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('course', 'code'), name='unique_coupon_per_course'),
        ),
    ]
