# Generated by Django 4.2.14 on 2024-11-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_username'),
        ('purchases', '0005_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user__role': 'student'}, related_name='applied_coupons', to='users.profile'),
        ),
    ]
