# Generated by Django 4.2.14 on 2024-11-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_intent',
            field=models.CharField(choices=[('cp', 'Course Purchase'), ('sp', 'Service Purchase'), ('mp', 'Membership Purchase'), ('ms', 'Monthly Subscription')], default='cp', max_length=300),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='CARD', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
