# Generated by Django 4.2.14 on 2024-11-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_currency_transaction_payment_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=46),
        ),
    ]
