# Generated by Django 4.2.14 on 2024-11-16 13:05

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_purchased_courses'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0006_remove_planfeature_plan_delete_membership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_billing_address', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('paypal', 'Paypal Account'), ('mpesa', 'MPesa Account'), ('bank', 'Bank Account')], default='bank', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.billingaddress')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PaypalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('payout_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_account', to='payments.payoutaccount')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('payout_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payoneer_account', to='payments.payoutaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('payout_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='payments.payoutaccount')),
            ],
        ),
    ]
