# Generated by Django 4.2.14 on 2024-11-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_payoutaccount_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutaccount',
            name='account_type',
            field=models.CharField(choices=[('paypal', 'Paypal Account'), ('mpesa', 'MPesa Account'), ('airtel', 'Airtel Account'), ('bank', 'Bank Account')], default='bank', max_length=10, unique=True),
        ),
    ]
