# Generated by Django 4.2.14 on 2024-11-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_purchased_courses'),
        ('payments', '0010_alter_payoutaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_transactions', to='users.profile'),
        ),
    ]
