# Generated by Django 4.2.14 on 2024-11-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_username'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0011_alter_transaction_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_choice', models.CharField(blank=True, max_length=100)),
                ('cleared', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_balance', to='users.profile')),
            ],
        ),
    ]
