# Generated by Django 4.2.14 on 2024-11-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_username'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('alert_message', models.CharField(blank=True, max_length=355)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profanity_score', models.PositiveBigIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_reviews', to='users.profile')),
            ],
        ),
    ]
