# Generated by Django 4.2.14 on 2024-11-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecurriculum',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_curriculum_profile', to='users.profile'),
        ),
        migrations.AddConstraint(
            model_name='coursecurriculum',
            constraint=models.UniqueConstraint(fields=('course', 'tutor', 'module_title'), name='unique_course_title'),
        ),
    ]
