# Generated by Django 4.2.14 on 2024-11-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_coursecurriculum_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_video_url',
            field=models.TextField(blank=True, help_text='\n        Please enter a valid video link or embedded URL or\n        live blank if no video is available'),
        ),
    ]
