# Generated by Django 4.2.14 on 2024-11-12 07:18

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_profile_first_name_profile_headline_and_more'),
        ('school', '0008_course_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=froala_editor.fields.FroalaField(help_text='Please make this a maximum of 5000 words'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_tutor', to='users.profile'),
        ),
    ]
