# Generated by Django 4.2.14 on 2024-11-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_lecture_has_free_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_video',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
