# Generated by Django 4.2.14 on 2024-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_course_preview_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
