# Generated by Django 4.2.14 on 2024-11-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_course_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='un_likes',
            field=models.IntegerField(default=0),
        ),
    ]
