# Generated by Django 4.2.14 on 2024-11-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_course_likes_course_un_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shared',
            field=models.IntegerField(default=11),
        ),
    ]
