# Generated by Django 4.2.14 on 2024-11-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_profile_first_name_profile_headline_and_more'),
        ('school', '0015_discussion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_replies', to='school.discussion')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_replies_profile', to='users.profile')),
            ],
        ),
    ]
