# Generated by Django 4.2.14 on 2024-11-13 08:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_discussion_message_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discussion',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
