# Generated by Django 4.2.14 on 2024-11-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_courseenrollment_courselecturecompletion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcourse',
            name='course',
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='courses',
            field=models.ManyToManyField(related_name='saved_courses', to='school.course'),
        ),
    ]
