# Generated by Django 4.2.14 on 2024-11-13 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_profile_first_name_profile_headline_and_more'),
        ('school', '0020_remove_savedcourse_course_savedcourse_courses'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.course'),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_subscriptions', to='users.profile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_subscriptions', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesubscription',
            unique_together={('subscription', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('tutor', 'student')},
        ),
    ]
