# Generated by Django 4.2.14 on 2024-11-13 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_profile_first_name_profile_headline_and_more'),
        ('school', '0021_alter_course_managers_coursesubscription_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesubscription',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='students',
            field=models.ManyToManyField(related_name='student_subscriptions', through='school.CourseSubscription', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tutor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_subscriptions', to='users.profile'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='student',
        ),
    ]
