# Generated by Django 4.2.14 on 2024-11-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_alter_coursesubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
