# Generated by Django 4.2.14 on 2024-11-16 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_course_course_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
