# Generated by Django 4.2.14 on 2024-11-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_alter_course_course_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
