# Generated by Django 4.2.14 on 2024-11-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_alter_course_course_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
