# Generated by Django 4.2.14 on 2024-11-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_profile_username'),
        ('school', '0026_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(auto_now_add=True, verbose_name='Attendance Date')),
                ('present', models.BooleanField(default=True, verbose_name='Present')),
                ('attendance_counter', models.IntegerField(default=1, verbose_name='Attendance Counter')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_attendance', to='school.course', verbose_name='Course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='users.profile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Course Attendance',
                'verbose_name_plural': 'Course Attendances',
            },
        ),
    ]
