# Generated by Django 4.2.14 on 2024-11-15 14:18

from django.db import migrations, models
import django.db.models.deletion
import roles.instructors.instructor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_profile_avatar'),
        ('payments', '0005_transaction_account_type_and_more'),
        ('school', '0022_alter_coursesubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='sales_course', to='school.course')),
                ('transactions', models.ManyToManyField(blank=True, related_name='course_sales', to='payments.transaction')),
                ('tutor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sales', to='users.profile', validators=[roles.instructors.instructor.models.validate_tutor_role])),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('salary', 'Salary'), ('penalty', 'Penalty'), ('transfer', 'Transfer')], default='deposit', max_length=10)),
                ('intent_reason', models.CharField(blank=True, max_length=300, validators=[roles.instructors.instructor.models.validate_intent_reason])),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('holder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_bank_account', to='users.profile')),
            ],
        ),
    ]
