# Generated by Django 4.2.14 on 2024-11-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesale',
            name='transactions',
        ),
    ]
