# Generated by Django 4.2.14 on 2024-11-17 22:14

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_alter_course_course_release_date'),
        ('instructor', '0003_coursesale_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_live_link', models.CharField(max_length=255)),
                ('login_required', models.BooleanField(default=True)),
                ('credentials', froala_editor.fields.FroalaField(help_text='Login credentials for the lesson')),
                ('class_time', models.DateTimeField()),
                ('short_url', models.CharField(blank=True, max_length=27)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_live_links', to='school.course')),
            ],
            options={
                'verbose_name': 'ScheduleClass',
                'verbose_name_plural': 'ScheduleClasses',
            },
        ),
    ]
