# Generated by Django 4.2.14 on 2024-11-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_scheduleclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleclass',
            options={'get_latest_by': 'class_time', 'ordering': ['-class_time'], 'verbose_name': 'ScheduleClass', 'verbose_name_plural': 'ScheduleClasses'},
        ),
    ]
