# Generated by Django 4.2.14 on 2024-11-18 21:07

from django.db import migrations, models
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_scheduleclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleclass',
            options={'get_latest_by': 'class_start_time', 'ordering': ['-class_start_time'], 'verbose_name': 'ScheduleClass', 'verbose_name_plural': 'ScheduleClasses'},
        ),
        migrations.RenameField(
            model_name='scheduleclass',
            old_name='class_time',
            new_name='class_end_time',
        ),
        migrations.AddField(
            model_name='scheduleclass',
            name='class_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleclass',
            name='lesson_overview',
            field=froala_editor.fields.FroalaField(default=django.utils.timezone.now, help_text='Login credentials for the lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduleclass',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
