# Generated by Django 4.2.14 on 2024-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_alter_coursesubscription_unique_together_and_more'),
        ('users', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='purchased_courses', to='school.course'),
        ),
    ]
