# Generated by Django 4.2.14 on 2024-11-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
