# Generated by Django 4.2.14 on 2024-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_planfeature_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
