# Generated by Django 4.2.14 on 2024-11-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_planfeature_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='feature',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature'),
        ),
    ]
