# Generated by Django 4.2.14 on 2024-11-15 18:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_planfeature_feature_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plan',
            managers=[
                ('basic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Tutor')], default='S', max_length=1, unique=True),
        ),
    ]
