# Generated by Django 4.2.14 on 2024-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_alter_plan_managers_alter_plan_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plan',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Cancelled'), ('P', 'Paused')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('S', 'Student'), ('I', 'Instructor')], default='S', max_length=1, unique=True),
        ),
    ]
