# Generated by Django 4.2.14 on 2024-11-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_purchased_courses'),
        ('memberships', '0007_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_membership', to='users.profile'),
        ),
    ]
