# Generated by Django 4.2.14 on 2024-11-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_purchased_courses'),
        ('memberships', '0008_alter_membership_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCardCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=24)),
                ('account_name', models.CharField(max_length=100)),
                ('account_cvv', models.CharField(max_length=200)),
                ('expiry_month', models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_card_capture', to='users.profile')),
            ],
        ),
    ]
